version: '3.1'
services:
    aws_comis:
        container_name: aws_comis
        image: comis:php
        build:
            context: ./php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./source:/var/www/html
            - ./log/httpd:/var/log/httpd
        extra_hosts:
            - "cosmic.jp:127.0.0.1"
        privileged: true
        networks:
            comis_net:
                ipv4_address: 192.25.0.5
    aruora_comis:
        container_name: aruora_comis
        image: atsnngs/mysql-aurora-compatible
        ports:
            - "13306:3306"
        volumes:
            - ./log/mysql:/var/log
        privileged: true
        networks:
            comis_net:
                ipv4_address: 192.25.0.3
networks:
    comis_net:
        driver: bridge
        ipam:
            config:
            - subnet: 192.25.0.0/24